version: '3.8'

services:
    mevent-postgres:
        container_name: mevent-postgres
        image: postgres:latest
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - ./.docker/conf/postgres/:/docker-entrypoint-initdb.d/
    mevent-auth-nginx:
        image: nginx:1.19-alpine
        container_name: mevent-auth-nginx
        restart: always
        ports:
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
    mevent-auth-php:
        container_name: mevent-auth-php
        build:
            context: ./
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./etc/php/php.ini:/usr/local/etc/php/php.ini
            - /tmp/xdebug:/tmp/xdebug
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - mevent-postgres
